# Generated by Django 5.1 on 2024-11-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serveradmin', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('video_url', models.URLField()),
                ('view_count', models.IntegerField(default=0)),
            ],
        ),
    ]
