# Generated by Django 5.1 on 2024-11-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveradmin', '0006_movie_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='file_path',
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.FileField(upload_to='uploads/thumb/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_url',
            field=models.FileField(upload_to='uploads/video/'),
        ),
    ]
