# Generated by Django 5.1 on 2024-11-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveradmin', '0007_remove_movie_file_path_alter_movie_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail_file',
            field=models.FileField(default=0, upload_to='uploads/thumb/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='video_file',
            field=models.FileField(default=0, upload_to='uploads/video/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_url',
            field=models.URLField(),
        ),
    ]
