# Generated by Django 5.1 on 2024-11-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serveradmin', '0008_movie_thumbnail_file_movie_video_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='thumbnail_file',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.FileField(upload_to='uploads/thumb/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_url',
            field=models.FileField(upload_to='uploads/video/'),
        ),
    ]
